version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk

    steps:
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          wget https://storage.googleapis.com/jbd-releases/gcp-connectivitytests-0.0.1 && chmod +x ./gcp-connectivitytests-0.0.1
          ./gcp-connectivitytests-0.0.1 -project=computelabs