version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk

    steps:
      - run: |
          apt-get install wget -y
          wget https://storage.googleapis.com/jbd-releases/gcp-connectivitytests-0.0.1-linuxamd64 && chmod +x ./gcp-connectivitytests-0.0.1-linuxamd64
          echo $GCLOUD_SERVICE_KEY > key.json
          GOOGLE_APPLICATION_CREDENTIALS=key.json ./gcp-connectivitytests-0.0.1-linuxamd64 -project=computelabs
